### ISSUE TITLE
Why is PHP 5.3 supported?

### ISSUE THREAD

**Issue by Potherca** [nerds-and-company/craft-api-authentication-plugin#6]
I saw the commits come by containing PHP 5.3 fixes.

The last version of PHP 5.3 has not been actively supported for _over a year_. 

Pardon my french, but **why the fuck are we actively supporting it**?

**Comment by boboldehampsink** [comment]
Because this is a public plugin for Craft, and Craft still supports 5.3.
I'm ok with dropping support for 5.3 tho, all major plugins are dropping 5.3 support nowadays.
Even Craft's own Commerce plugin is 5.4+. 

Should we document this somewhere?

**Comment by Potherca** [comment]
Yes. For this repository is should be enough to bump the PHP version in the `composer.json`.
The question still remains where _else_ we need to document this for other projects.

My guess would be somewhere near the documentation on how we set up a Travis build (and config file).

So the question is where have we documented that?

**Comment by boboldehampsink** [comment]
We don't officially use travis as an organization, so nowhere ;-)

**Comment by Potherca** [comment]
:-/ I'm assuming that most projects also either won't have a `composer.json` or, if they do, won't have their PHP version and required PHP extensions declared.

Maybe we should start with documenting _that_ somewhere first.

I think the [guides repo](https://github.com/nerds-and-company/nerd-guides) is the best place for it. I'll open an issue there.

**Comment by boboldehampsink** [comment]
Agreed

**Comment by Potherca** [comment]
Closing this issue as I no longer have access to the linked repository and no longer  use Craft.
